"""fix settings and deps

Revision ID: 990f2a6de7d0
Revises: aff1c0c69f3f
Create Date: 2025-08-08 17:17:05.686732

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "990f2a6de7d0"
down_revision: Union[str, Sequence[str], None] = "aff1c0c69f3f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
